# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c03fa581dc763fe12b938d51e363e72ae20ba1b267b1a569d24bb2bbd4fc57ec6352ed5e145681a4ce8f50c08a5367c516826db2d173538eacb33a0f7013fea3

test:
  secret_key_base: 173aa2afd165c9ed2b54570e18470dc6655bba8a825cc6ae424a004d329a04b1260c81c482355d92830388557d7fb2a39e326f52d337ef2943806e688d0e0255

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
